local Util = require("solaris.util")

local M = {}

---@type solaris.HighlightsFn
function M.get(c, opts)
  -- stylua: ignore
  local ret = {
    -- BeardedBear mapping:
    -- blue=functions, green=strings, yellow=keywords, purple=types,
    -- orange=accessors, pink=decorators/args, red=constants,
    -- turquoize=storage/special, salmon=variables
    ["@annotation"]                 = "PreProc",
    ["@attribute"]                  = { fg = c.pink },
    ["@boolean"]                    = { fg = c.red },
    ["@character"]                  = "Character",
    ["@character.printf"]           = "SpecialChar",
    ["@character.special"]          = "SpecialChar",
    ["@comment"]                    = "Comment",
    ["@comment.error"]              = { fg = c.error },
    ["@comment.hint"]               = { fg = c.hint },
    ["@comment.info"]               = { fg = c.info },
    ["@comment.note"]               = { fg = c.hint },
    ["@comment.todo"]               = { fg = c.todo },
    ["@comment.warning"]            = { fg = c.warning },
    ["@constant"]                   = { fg = c.red },
    ["@constant.builtin"]           = { fg = c.red },
    ["@constant.macro"]             = "Define",
    ["@constructor"]                = { fg = c.purple },
    ["@constructor.tsx"]            = { fg = c.purple },
    ["@diff.delta"]                 = "DiffChange",
    ["@diff.minus"]                 = "DiffDelete",
    ["@diff.plus"]                  = "DiffAdd",
    ["@function"]                   = "Function",
    ["@function.builtin"]           = { fg = c.blue },
    ["@function.call"]              = "@function",
    ["@function.macro"]             = "Macro",
    ["@function.method"]            = "Function",
    ["@function.method.call"]       = "@function.method",
    ["@keyword"]                    = { fg = c.yellow, style = opts.styles.keywords },
    ["@keyword.conditional"]        = { fg = c.yellow, style = opts.styles.keywords },
    ["@keyword.coroutine"]          = "@keyword",
    ["@keyword.debug"]              = "Debug",
    ["@keyword.directive"]          = "PreProc",
    ["@keyword.directive.define"]   = "Define",
    ["@keyword.exception"]          = { fg = c.yellow },
    ["@keyword.function"]           = { fg = c.turquoize, style = opts.styles.functions },
    ["@keyword.import"]             = { fg = c.yellow },
    ["@keyword.operator"]           = { fg = c.turquoize },
    ["@keyword.repeat"]             = { fg = c.yellow, style = opts.styles.keywords },
    ["@keyword.return"]             = "@keyword",
    ["@keyword.storage"]            = { fg = c.turquoize },
    ["@label"]                      = { fg = c.blue },
    ["@markup"]                     = "@none",
    ["@markup.emphasis"]            = { italic = true },
    ["@markup.environment"]         = "Macro",
    ["@markup.environment.name"]    = "Type",
    ["@markup.heading"]             = "Title",
    ["@markup.italic"]              = { italic = true },
    ["@markup.link"]                = { fg = c.teal },
    ["@markup.link.label"]          = "SpecialChar",
    ["@markup.link.label.symbol"]   = "Identifier",
    ["@markup.link.url"]            = "Underlined",
    ["@markup.list"]                = { fg = c.turquoize },
    ["@markup.list.checked"]        = { fg = c.green },
    ["@markup.list.markdown"]       = { fg = c.orange, bold = true },
    ["@markup.list.unchecked"]      = { fg = c.blue },
    ["@markup.math"]                = "Special",
    ["@markup.raw"]                 = "String",
    ["@markup.raw.markdown_inline"] = { bg = c.terminal_black, fg = c.blue },
    ["@markup.strikethrough"]       = { strikethrough = true },
    ["@markup.strong"]              = { bold = true },
    ["@markup.underline"]           = { underline = true },
    ["@module"]                     = { fg = c.orange },
    ["@module.builtin"]             = { fg = c.orange },
    ["@namespace.builtin"]          = "@variable.builtin",
    ["@none"]                       = {},
    ["@number"]                     = { fg = c.red },
    ["@number.float"]               = { fg = c.red },
    ["@operator"]                   = { fg = c.turquoize },
    ["@property"]                   = { fg = c.orange },
    ["@punctuation.bracket"]        = { fg = c.fg_dark },
    ["@punctuation.delimiter"]      = { fg = c.fg_dark },
    ["@punctuation.special"]        = { fg = c.turquoize },
    ["@punctuation.special.markdown"] = { fg = c.orange },
    ["@string"]                     = "String",
    ["@string.documentation"]       = { fg = c.green },
    ["@string.escape"]              = { fg = c.turquoize },
    ["@string.regexp"]              = { fg = c.turquoize },
    ["@tag"]                        = { fg = c.red },
    ["@tag.attribute"]              = { fg = c.orange },
    ["@tag.delimiter"]              = { fg = c.fg_dark },
    ["@tag.delimiter.tsx"]          = { fg = Util.blend_bg(c.blue, 0.7) },
    ["@tag.tsx"]                    = { fg = c.red },
    ["@tag.javascript"]             = { fg = c.red },
    ["@type"]                       = "Type",
    ["@type.builtin"]               = { fg = Util.blend_bg(c.purple, 0.8) },
    ["@type.definition"]            = "Typedef",
    ["@type.qualifier"]             = "@keyword",
    ["@variable"]                   = { fg = c.salmon, style = opts.styles.variables },
    ["@variable.builtin"]           = { fg = c.salmon },
    ["@variable.member"]            = { fg = c.orange },
    ["@variable.parameter"]         = { fg = c.pink },
    ["@variable.parameter.builtin"] = { fg = Util.blend_fg(c.pink, 0.8) },
  }

  for i, color in ipairs(c.rainbow) do
    ret["@markup.heading." .. i .. ".markdown"] = { fg = color, bold = true, bg = Util.blend_bg(color, 0.1) }
  end
  return ret
end

return M
